[package]
name = "formsbox-stress-test-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
md5 = "0.7"

